DROP TABLE IF EXISTS learning_report;
DROP TABLE IF EXISTS answer_record;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS material_chunk;
DROP TABLE IF EXISTS material;
DROP TABLE IF EXISTS source_material;
DROP TABLE IF EXISTS learning_session;

CREATE TABLE learning_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  title VARCHAR(255) NOT NULL,
  input_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  question_count INT NOT NULL DEFAULT 0,
  correct_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE source_material (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  type VARCHAR(32) NOT NULL,
  content CLOB NULL,
  source_url VARCHAR(1024) NULL,
  file_url VARCHAR(1024) NULL,
  parsed_text CLOB NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE material (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(32) NOT NULL,
  file_name VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL,
  chunk_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE material_chunk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id BIGINT NOT NULL,
  chunk_index INT NOT NULL,
  content CLOB NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE question (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  question_type VARCHAR(32) NOT NULL,
  stem CLOB NOT NULL,
  options_json CLOB NOT NULL,
  correct_answer VARCHAR(255) NOT NULL,
  explanation CLOB NOT NULL,
  knowledge_point VARCHAR(255) NOT NULL,
  difficulty VARCHAR(32) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_url VARCHAR(1024) NOT NULL,
  evidence_text CLOB NOT NULL,
  confidence DECIMAL(4,3) NOT NULL,
  sort_order INT NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE answer_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  question_id BIGINT NOT NULL,
  user_answer VARCHAR(255) NOT NULL,
  correct TINYINT NOT NULL,
  explanation CLOB NOT NULL,
  answered_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_session_question UNIQUE (session_id, question_id)
);

CREATE TABLE learning_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  summary CLOB NOT NULL,
  mastery CLOB NOT NULL,
  score INT NOT NULL,
  accuracy DECIMAL(5,2) NOT NULL,
  weak_points_json CLOB NOT NULL,
  suggestions_json CLOB NOT NULL,
  wrong_questions_json CLOB NOT NULL,
  created_at TIMESTAMP NOT NULL
);
